apiVersion: apps/v1
kind: Deployment
metadata:
  name: passbolt-deployment
spec:
  selector:
    matchLabels:
      app: passbolt
  replicas: 3
  template:
    metadata:
      labels:
        app: passbolt
    spec:
      containers:
        - name: passbolt
          image: dragoneena/passbolt:2.13.5-arm64
          ports:
            - containerPort: 80
