apiVersion: apps/v1
kind: Deployment
metadata:
  name: passbolt
spec:
  selector:
    matchLabels:
      app: passbolt
  replicas: 3
  template:
    metadata:
      labels:
        app: passbolt
    spec:
      containers:
        - name: passbolt
          image: dragoneena12/passbolt:2.13.5-arm64
          ports:
            - containerPort: 443
          env:
            - name: DATASOURCES_DEFAULT_HOST
              value: passbolt-db
            - name: DATASOURCES_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passbolt
                  key: user_password
            - name: DATASOURCES_DEFAULT_USERNAME
              value: passbolt
            - name: DATASOURCES_DEFAULT_DATABASE
              value: passbolt
            - name: APP_FULL_BASE_URL
              value: https://passbolt.lapi.gq
