apiVersion: v1
kind: Service
metadata:
  name: passbolt-db
spec:
  ports:
    - port: 3306
  selector:
    app: passbolt-db
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: passbolt-db
spec:
  selector:
    matchLabels:
      app: passbolt-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: passbolt-db
    spec:
      containers:
        - image: mariadb:10.5.5
          name: passbolt-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passbolt
                  key: root_password
            - name: MYSQL_DATABASE
              value: passbolt
            - name: MYSQL_USER
              value: passbolt
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passbolt
                  key: user_password
          ports:
            - containerPort: 3306
              name: passbolt-db
          volumeMounts:
            - name: passbolt-db-persistent-storage
              mountPath: /var/lib/db
      volumes:
        - name: passbolt-db-persistent-storage
          persistentVolumeClaim:
            claimName: passbolt-db-pv-claim
